version: "3.0"
services:
  ranchervm:
    image: rancher/ranchervm
    container_name: ranchervm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/ranchervm:/ranchervm
      - /var/run:/var/run
    ports:
      - 8082:80
    restart: unless-stopped
    labels:
      - "traefik.http.routers.ranchervm.rule=Host(`vm.tlss1.lan`)"